info:
  name: a.us.gov
  ttl_seconds: 30

server_config:
  secret: 123123xxx
  api: http://127.0.0.1:3210

time_policy:
  scan_time_seconds: 10
  min_report_time_seconds: 500

functions:
  log:
    write_log_file: True
